services:
  cityflow_database:
    build:
      context: ./cityflow_database
      dockerfile: Dockerfile
      platforms:
        - 'linux/amd64'
        - 'linux/arm64'
    image: ghcr.io/kekehurry/cityflow_database:latest
    ports:
      - '7474:7474'
      - '7687:7687'
      - '7575:7575'
    user: '501:20'
    volumes:
      - ./cityflow_database/data:/data
    env_file:
      - .env
    privileged: true
    restart: always
    networks:
      - cityflow

  cityflow_executor:
    build:
      context: ./cityflow_executor
      dockerfile: Dockerfile
      platforms:
        - 'linux/amd64'
        - 'linux/arm64'
    image: ghcr.io/kekehurry/cityflow_executor:latest
    ports:
      - '8000:8000'
    user: '501:20'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./cityflow_executor/code:/workspace/code
    env_file:
      - .env
    privileged: true
    restart: always
    networks:
      - cityflow

  cityflow_workstation:
    build:
      context: ./cityflow_workstation
      dockerfile: Dockerfile
      platforms:
        - 'linux/amd64'
        - 'linux/arm64'
    image: ghcr.io/kekehurry/cityflow_workstation:latest
    ports:
      - '3000:3000'
    user: '501:20'
    env_file:
      - .env
    privileged: true
    restart: always
    networks:
      - cityflow

networks:
  cityflow:
    driver: bridge
