services:
  cityflow_platform:
    image: ghcr.io/kekehurry/cityflow_platform:latest
    container_name: cityflow_platform
    ports:
      - '3000:3000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./cityflow_executor/code:/cityflow_executor/code
      - ./cityflow_database/data:/data
      - ./cityflow_database/source:/cityflow_database/source
    user: '501:20'
    env_file:
      - .env
    restart: 'always'
    networks:
      - cityflow

networks:
  cityflow:
    driver: bridge
