name: Build and Push to GHCR

on:
  push:
    branches: [ dev ]

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Install QEMU 7.0
      run: |
        sudo apt update && sudo apt upgrade -y
        sudo apt install make ninja-build libpixman-1-dev -y
        wget https://download.qemu.org/qemu-7.0.0.tar.xz
        tar xvJf qemu-7.0.0.tar.xz
        cd qemu-7.0.0
        ./configure
        make
        sudo make install

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push City Flwo Platform
      uses: docker/build-push-action@v6.10.0
      with:
        context: ./
        file: ./Dockerfile
        tags: ghcr.io/kekehurry/cityflow_platform:dev
        platforms: linux/arm64,linux/amd64
        push: true
