name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to gitea
      uses: docker/login-action@v2
      with:
        registry: git.arhukai.com
        username: kekehurry
        password: WHOCAN931111a

    - name: Build and Push City Flwo Platform
      uses: docker/build-push-action@v6.10.0
      with:
        context: ./
        file: ./Dockerfile
        tags: kekehurry/cityflow_platform
        platforms: linux/amd64,linux/arm64
        push: true
        

      
        
      
      
